services:
  - type: web
    name: lms-learnit
    runtime: docker
    plan: free
    region: oregon
    rootDir: learning-management-main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGINS
        sync: false
